language: node_js
sudo: false

node_js:
  - '8'
  - '10'

env:
  global:
    - TIMEOUT_MULTIPLIER=8
  matrix:
    - SENECA_VERSION=senecajs/seneca#plugin
    - SENECA_VERSION=senecajs/seneca


install:
  - NODE_VERSION=$(node -v); if [ ${NODE_VERSION:1:2} -ge 10 ]; then npm i -g npm@6; npm ci; else npm install; fi



before_script:
  - echo "SENECA_VERSION:${SENECA_VERSION}";
  - npm uninstall seneca;
  - npm install "$SENECA_VERSION";


script:
  - npm test
  - if [ ${NODE_VERSION:1:2} -ge 10 ]; then npm audit; fi


cache:
  directories:
    - "$HOME/.npm"

