language: node_js
sudo: false

node_js:
  - '8'
  - '10'

env:
  global:
    - TIMEOUT_MULTIPLIER=8
  matrix:
#    - SENECA_VERSION=seneca@plugin
    - SENECA_VERSION=senecajs/seneca

before_script:
  - npm uninstall seneca;
  - npm install "$SENECA_VERSION";

script:
  - npm test

cache:
  directories:
    - "$HOME/.npm"

